### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, int found

### ISSUE THREAD

**Issue by chicungunya** [fugkco/script.elementum.jackett#4]
Hi @fugkco 
I tried your new version and there is a problem with YGG : TypeError: coercing to Unicode: need string or buffer, int found

This is my log : https://paste.kodi.tv/ekofidaqug.kodi

Thanks a lot !

**Comment by dairefagan** [comment]
Edit: My mistake, I have observed a different Unicode error, not the same as this: https://github.com/fugkco/script.elementum.jackett/issues/5

**Comment by fugkco** [comment]
@chicungunya the log is gone, can you upload it again?

**Comment by tsiktsiris** [comment]
Hello, I am also looking into this.

> 2020-11-29 11:21:32.709 T:1026519936  NOTICE: [script.elementum.jackett] Could not determine search title, falling back to normal title: u'fantasy island'
2020-11-29 11:21:33.206 T:1026519936  NOTICE: [script.elementum.jackett] Found capabilities: {'search_tags': {'search': {'params': ['q'], 'enabled': True}, 'tv-search': {'params': ['q', 'season', 'ep'], 'enabled': True}, 'book-search': {'params': ['q'], 'enabled': True}, 'music-search': {'params': ['q'], 'enabled': True}, 'movie-search': {'params': ['q'], 'enabled': True}, 'audio-search': {'params': ['q'], 'enabled': True}}}
2020-11-29 11:21:33.209 T:1026519936   ERROR: [script.elementum.jackett] Traceback (most recent call last):
2020-11-29 11:21:33.209 T:1026519936   ERROR: [script.elementum.jackett]   File "/storage/.kodi/addons/plugin.video.elementum/resources/site-packages/elementum/provider.py", line 168, in register
2020-11-29 11:21:33.209 T:1026519936   ERROR: [script.elementum.jackett]     objects = method(payload["search_object"])
2020-11-29 11:21:33.209 T:1026519936   ERROR: [script.elementum.jackett]   File "/storage/.kodi/addons/script.elementum.jackett/jackett.py", line 31, in <lambda>
2020-11-29 11:21:33.210 T:1026519936   ERROR: [script.elementum.jackett]     lambda q: search(q, 'movie'),
2020-11-29 11:21:33.210 T:1026519936   ERROR: [script.elementum.jackett]   File "/storage/.kodi/addons/script.elementum.jackett/src/jackett.py", line 64, in search
2020-11-29 11:21:33.210 T:1026519936   ERROR: [script.elementum.jackett]     results = search_jackett(payload, method)
2020-11-29 11:21:33.210 T:1026519936   ERROR: [script.elementum.jackett]   File "/storage/.kodi/addons/script.elementum.jackett/src/jackett.py", line 170, in search_jackett
2020-11-29 11:21:33.211 T:1026519936   ERROR: [script.elementum.jackett]     res = jackett.search_movie(payload["search_title"], payload['year'], payload["imdb_id"])
2020-11-29 11:21:33.211 T:1026519936   ERROR: [script.elementum.jackett]   File "/storage/.kodi/addons/script.elementum.jackett/src/client.py", line 114, in search_movie
2020-11-29 11:21:33.211 T:1026519936   ERROR: [script.elementum.jackett]     request_params["q"] = title + u' ' + year
2020-11-29 11:21:33.211 T:1026519936   ERROR: [script.elementum.jackett] TypeError: coercing to Unicode: need string or buffer, int found

**Comment by tsiktsiris** [comment]
@fugkco 
_year_ variable in the following line is integer:
https://github.com/fugkco/script.elementum.jackett/blob/dc738ceb07fe72c0e74f18ca3bae32a553962322/src/client.py#L114

Used the str() function to convert and it's working fine:
`            request_params["q"] = title + u' ' + str(year)`

**Comment by fugkco** [comment]
This should be fixed in https://github.com/fugkco/script.elementum.jackett/releases/tag/v2.0.1 via #14.
